name: nativa_bc
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # streaming de áudio + background & lock-screen controls
  just_audio: ^0.9.30
  audio_service: ^0.18.0
  audio_session: ^0.1.6

  # para abrir URLs (WhatsApp, redes sociais, e-mail, site)
  url_launcher: ^6.1.5

  # notificações locais
  flutter_local_notifications: ^19.1.0

  # checagem de versão
  package_info_plus: ^8.3.0
  font_awesome_flutter: ^10.1.0
  video_player: ^2.5.1

  # HTTP (alinhado com todas as dependências acima)
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  http: ^1.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/bg.mp4
    - assets/logo.png
    - assets/fundo.png
